# Generated by Django 5.0.4 on 2024-05-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listmodel",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
