# Generated by Django 5.0.4 on 2024-05-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typemodel",
            name="type_name",
            field=models.CharField(
                default="Default", max_length=25, unique=True, verbose_name="Type name"
            ),
        ),
    ]
