# Generated by Django 5.0.4 on 2024-05-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_alter_listmodel_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listmodel",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
